apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: game-backend-uploads-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi 